### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nisrinemr1** [bizarre/notion-embeds#1]
Hey, I tried to link it to my notion but doesn't works.. I don't understand why when I past the link on notion it add 25 after the %

**Comment by bizarre** [comment]
Could you link your document? I haven't personally used this in awhile but I just tried it out and it's working on my end?

[[Demo]](https://wiggly-hook-4f2.notion.site/e46fe6bc9c9042ce9df4471b1b86648b)


URL in above is https://notion-github-embed.vercel.app/chart/bizarre.

**Comment by nisrinemr1** [comment]
Oh okay it works ! thanks!
