### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by aichaun** [bizarre/notion-embeds#3]
not sure why it's not working, but it gives me this. Even from your demo that I found in an earlier (closed) issue here, it gives the same result.
![Screenshot_112](https://github.com/bizarre/notion-embeds/assets/39998825/d27a912a-66bd-4eca-924b-ac7f9868b0f9)

**Comment by bizarre** [comment]
looks to be working for me: https://notion-github-embed.vercel.app/chart/bizarre
